services:
  - type: web
    name: mutcd-ai-backend  # Matches your service name
    env: python  # Forces Python runtime (no Poetry)
    buildCommand: apt-get update -qq && apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: XAI_API_KEY
        sync: false  # Keeps it dashboard-only (secure)
    autoDeploy: true
